### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by MetaMmodern** [owlsdepartment/vite-plugin-babel#10]
I don't understand how to use this plugin. I get an error with a simple code like this:

vite.config.js:
```js
import { defineConfig } from "vite";
import vitePluginString from "vite-plugin-string";
import loadVersion from "vite-plugin-package-version";

import babel from "vite-plugin-babel";

export default ({ mode }) => {
  return defineConfig({
    server: {
      proxy: {
        "/api": {
          target: "http://localhost:8080",
          changeOrigin: true,
          secure: false,
        },
      },
    },
    plugins: [
      babel(),
      loadVersion(),
      vitePluginString({
        include: ["**/*.html"],
        exclude: ["node_modules/**", "./index.html"],
      }),
      ViteEjsPlugin(),
    ],
  });
};
```
.babelrc.js:
```js
"use strict";

module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        modules: "auto",
      },
    ],
  ],
  // plugins: [
  //   [
  //     "babel-plugin-ng-hot-reload",
  //     {
  //       angularGlobal: "angular",
  //     },
  //   ],
  // ],
};

```

index.js:
```js
import _ from "lodash";
```
And it gives me this error:
`Ucaught ReferenceError: require is not defined`
 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/42899786/232868770-ed06208b-d040-4733-ab40-77bdaabf2820.png">

What am I doing wrong? Would be really good if you had an example repo that uses this plugin

**Comment by F0rsaken** [comment]
it's not plugin's fault. Babel is translating your code to CommonJS style with `require` import which means, your Babel config is wrong. Try setting `modules` to `false`

**Comment by MetaMmodern** [comment]
Yes, that was correct, wow guys that was really fast ahah) I was just going to write it here and close the ticket. Thank you
