### ISSUE TITLE
Can not work with core-js by .babelrc & .browserslistrc

### ISSUE THREAD

**Issue by jerrywu001** [owlsdepartment/vite-plugin-babel#11]
### Describe the bug

For example, if I use `''.padStart` with .browserlistrc `>0.2%`, It should be auto polyfill with `babel-preset-env`.

The result should be:
 [demo with @rollup/plugin-babel is ok](https://stackblitz.com/edit/vitejs-vite-7gfghf?file=.browserslistrc,.babelrc,src%2Ftest.ts,vite.config.ts):

![image](https://user-images.githubusercontent.com/12525415/234176767-1ff7c941-0cb3-479c-96e4-45412d6e4bee.png)

**But there is no polyfill with core-js.**

![image](https://user-images.githubusercontent.com/12525415/234177070-977f91e8-7101-47e7-9d13-b419d5ae6b54.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vw37wc?file=.babelrc,.browserslistrc,src%2Ftest.ts,vite.config.ts

### Steps to reproduce

- npm install
- npm run build
- then open dist/index.[hash].js

Has no polyfill with core-js.

![image](https://user-images.githubusercontent.com/12525415/234177070-977f91e8-7101-47e7-9d13-b419d5ae6b54.png)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^4.0.0-beta.0 => 4.0.0 
    @vitejs/plugin-react-swc: ^3.3.0 => 3.3.0 
    vite: ^4.3.1 => 4.3.1
```

### Used Package Manager

npm

**Comment by F0rsaken** [comment]
hi @jerrywu001 

this Vite plugin is run ONLY on server mode, not during build 😄 
in your `vite.config` setup you are already using `@vitejs/plugin-react` (https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#babel) which already includes babel, so you should be good without our `vite-plugin-babel`

**Comment by jerrywu001** [comment]
> hi @jerrywu001
> 
> this Vite plugin is run ONLY on server mode, not during build 😄
> 
> also, in your `vite.config` setup you are already using `@vitejs/plugin-react` (https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#babel) which already includes babel, so you should be good without our `vite-plugin-babel`

plugin-react can not polyfill also
