### ISSUE TITLE
Support all valid Javascript regex

### ISSUE THREAD

**Issue by blikblum** [owlsdepartment/vite-plugin-babel#12]
As pointed in https://github.com/owlsdepartment/vite-plugin-babel/issues/1#issuecomment-1155178454,  filter with lookarounds are not supported by esbuild/go.

This is odd because such regex works in build but not in serve

The workaround is to pass an match all filter to esbuild and test with javascript regex inside the callback: https://github.com/evanw/esbuild/issues/1634#issuecomment-927204088 like is done for rollup / build: https://github.com/owlsdepartment/vite-plugin-babel/blob/master/index.ts#L40 

If performance is a concern (i dont believe should be noticeable) an option could be added

I can open a PR

BTW this is the regex i'm using:
`
/^(?!.*node_modules(?!.*luipack)).*\.jsx?$/`  

I want to skip all files from node_modules except the ones from luipack package

**Comment by F0rsaken** [comment]
I merged it and released in 1.2.0. Thx for contribution! 🙌
