### ISSUE TITLE
Add include, exclude options

### ISSUE THREAD

**Issue by blikblum** [owlsdepartment/vite-plugin-babel#13]
In rollup ecosystem there's a convention to use `include`, `exclude` options. It creates a more flexible  way to define what to parse.

There's a `createFilter` function exported by [@rollup/pluginutils](https://www.npmjs.com/package/@rollup/pluginutils) to create a filter from `exclude` and  `include` options https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/createFilter.ts#L26

**Comment by F0rsaken** [comment]
Great suggestion! I released it in `1.2.0`! :D
