### ISSUE TITLE
Can't enable decorators syntax

### ISSUE THREAD

**Issue by kkollman** [owlsdepartment/vite-plugin-babel#14]
Hello there, 

I am struggling with enabling legacy decorator syntax. I am migrating large react app from CRA to Vite. One of the core parts of the app is Mobx and our codebase relies heavily on decorators. I have enabled all the plugins previously used in `.babelrc` as part of plugin configuration in new `vite.config.js`, but I still get the `JavaScript decorators are not currently supported` error. What can be the source of the issue? I tried to change the order of the plugins but that didn't work either.

My current vite config file:

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'fs/promises';
import babel from 'vite-plugin-babel';
import svgr from 'vite-plugin-svgr';

// https://vitejs.dev/config/
export default defineConfig({
  esbuild: {
    loader: 'jsx',
    include: /src\/.*\.jsx?$/,
    exclude: [],
  },
  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        {
          name: 'load-js-files-as-jsx',
          setup(build) {
            build.onLoad({ filter: /src\/.*\.js$/ }, async args => ({
              loader: 'jsx',
              contents: await fs.readFile(args.path, 'utf8'),
            }));
          },
        },
      ],
    },
  },
  plugins: [
    react(),
    babel({
      babelConfig: {
        plugins: [
          ['@babel/plugin-proposal-export-default-from'],
          ['@babel/plugin-proposal-decorators', { legacy: true }],
          ['@babel/plugin-proposal-class-properties', { loose: false }],
          ['@babel/plugin-proposal-optional-chaining'],
          ['@babel/plugin-proposal-nullish-coalescing-operator'],
          [
            'formatjs',
            {
              messagesDir: './translations/messages/',
              idInterpolationPattern: '[sha512:contenthash:base64:6]',
              ast: true,
            },
          ],
        ],
      },
    }),
    svgr(),
  ],
  build: {
    outDir: 'build',
  },
  server: {
    open: true,
  },
  resolve: {
    alias: {
      src: '/src',
    },
  },
});
```

**Comment by F0rsaken** [comment]
hi @kkollman ,

I don't think you should use this plugin for your case. `@vitejs/plugin-react` already comes with babel, so maybe there's a conflict there, and you should just configure `react()` plugin, similarly to docs: https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#babel

**Comment by kkollman** [comment]
Thanks for quick reply, @F0rsaken ! Thanks, I'll try that approach :)

**Comment by F0rsaken** [comment]
Happy to help, Let me know if it would work for you, if not, we will try to think about another solution ^^

**Comment by kkollman** [comment]
@F0rsaken yes, relying on react() plugin did the work! Thank you :) I am closing the issue now.

**Comment by mathiaswillburger** [comment]
> @F0rsaken yes, relying on react() plugin did the work! Thank you :) I am closing the issue now.

Could you share how your final `vite.config.js` looks like to make it work? I am running into exactly the same issue with MobX.

**Comment by kkollman** [comment]
@mathiaswillburger sure thing! So, relying on this config did the work:

```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        presets: ['@babel/preset-react'],
        plugins: [
          ['@babel/plugin-proposal-export-default-from'],
          ['@babel/plugin-proposal-class-properties', { loose: false }],
          ['@babel/plugin-proposal-decorators', { legacy: true }],
          ['@babel/plugin-proposal-optional-chaining'],
          ['@babel/plugin-proposal-nullish-coalescing-operator'],
          [
            'formatjs',
            {
              messagesDir: './translations/messages/',
              idInterpolationPattern: '[sha512:contenthash:base64:6]',
              ast: true,
            },
          ],
        ],
      },
    }),
    svgr(),
  ],
});
```

However, I must admit that after doing some research and trying out a couple of different approaches, I finally gave up and removed decorators completely from my codebase. Since mobx provides [codemod](https://www.npmjs.com/package/mobx-undecorate) that helps you to move away from decorators even if you previously used them, I would recommend going that way. Otherwise, you may find yourself struggling with compatibility with other tools (like storybook or testing libraries for example).

**Comment by mathiaswillburger** [comment]
@kkollman thanks for the example and the hint for the codemod! That helped and I got it working now. But I will definitely look into removing the decorators too.
