### ISSUE TITLE
vue files are not supported？

### ISSUE THREAD

**Issue by aiyadingya** [owlsdepartment/vite-plugin-babel#19]
```
  const babelConfig = babel({
    apply: 'serve',
    babelConfig: {
      babelrc: false,
      configFile: false,
      plugins: ['@babel/plugin-transform-optional-chaining', '@babel/plugin-transform-nullish-coalescing-operator']
    },
    filter: /\.(jsx?$)|vue$/
  })
```

**Comment by F0rsaken** [comment]
If you want to use Vue files, I think you should just go with the [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md)

**Comment by jingjingshenye** [comment]
> If you want to use Vue files, I think you should just go with the [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md)

the plugin can support vue file decorators ?

**Comment by F0rsaken** [comment]
> > If you want to use Vue files, I think you should just go with the [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md)
> 
> the plugin can support vue file decorators ?

TBH, never had to make a combination like that. I think you would need to combine both plugins. First one is [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/README.md) and later on babel plugin, but I never tested it out. I will try to replicate it and I'll get to you later with a specific answer ;)
