### ISSUE TITLE
Error: You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously

### ISSUE THREAD

**Issue by vonBrax** [owlsdepartment/vite-plugin-babel#21]
Hey, thanks for your work here!

We recently switched our repo to use ESM only and then stumbled upon this error. Apparently babel only works with ESM if we use babel.transformAsync instead of babel.transformSync.

![babel_async](https://github.com/owlsdepartment/vite-plugin-babel/assets/17157482/382b1acc-d93c-4491-b4a0-480c0e6ca99e)

We are using
* "@babel/cli": "7.23.4"
* "@babel/core": "7.23.6"
* "vite-plugin-babel": "1.1.3"

I'm creating a PR for this, seems like a simple fix.

**Comment by F0rsaken** [comment]
I merged it and released in `1.2.0`. Thx for contribution! 🙌
