### ISSUE TITLE
Is it possible to support filter as a function?

### ISSUE THREAD

**Issue by Jinjiang** [owlsdepartment/vite-plugin-babel#25]
First of all, a very great plugin!

The issue is about supporting the `filter` as a function like `(id: string) => boolean` in [`@rollup/plugin-babel`](https://github.com/rollup/plugins/tree/master/packages/babel#filter)

The background is I'm migrating a babel config from webpack to Vite, in which it filters files by detecting a field in its closest `package.json`. The logic is complex which requires a function to do that instead of a RegExp.

Thanks.

**Comment by F0rsaken** [comment]
Thanks! It's nice to hear! ^^

I checked in the code and it sohuldn't be a problem to add that

**Comment by F0rsaken** [comment]
allowed for a `filter` to accept a function in `1.3.0`. Let me know if it works 👌

**Comment by Jinjiang** [comment]
It works! Thanks so much!
