### ISSUE TITLE
Upgrade to vite 3?

### ISSUE THREAD

**Issue by winston0410** [owlsdepartment/vite-plugin-babel#4]
Will this plugin upgrade to vite 3?

**Comment by F0rsaken** [comment]
good issue, I plan on doing it, but need some time, probably this or next weekend

**Comment by F0rsaken** [comment]
I looked over changes in `vite@3` and seems that nothing needs to be updated, so I only made a patch with proper peer dependencies range. If you will find any bugs, let me know
