### ISSUE TITLE
Node 12 is not supported

### ISSUE THREAD

**Issue by chengzhuo5** [owlsdepartment/vite-plugin-babel#7]
error when starting dev server:
contents: result?.code ?? "",
                         ^
SyntaxError: Unexpected token '.'

**Comment by przyb** [comment]
@chengzhuo5 which version of Node are you running?

**Comment by przyb** [comment]
@chengzhuo5 Node 12 is EOL since 2022-04-30, so we don't plan to support it. Please update to 16 which is the current stable LTS.
