### ISSUE TITLE
Support for vite 4

### ISSUE THREAD

**Issue by susnux** [owlsdepartment/vite-plugin-babel#9]
Currently the peer dependencies restrict vite to `vite@"^2.7.0 || ^3.0.0"` but vite 4 is already available.
Is this plugin compatible?

**Comment by F0rsaken** [comment]
I went through migration guide of `Vite 4`, and I don't see any breaking changes that would affect this plugin. I will bump peer dependencies to `^4.0.0` in the near future. Let me know if you find any bugs!

**Comment by F0rsaken** [comment]
Updaten in version `v1.1.3`
